Para este projeto, será utilizado o gerenciador de pacotes Python chamado "uv". <br>
Documentação: https://docs.astral.sh/uv/

De forma inicial: uv init <br>
(Versionamento do projeto com git e cria uma estrutura organizada de pastas, exemplo: .venv // .gitignore // .python-version // main.py // pyproject.toml // README.md)

uv add pandas
uv add numpy <br>
(Ao adicionar bibliotecas ao projeto, as bibliotecas são adicionadas no arquivo pyproject.toml. A cada inserção/atualização de bibliotecas, o arquivo .toml é atualizado)

Importando as bibliotecas Python:

In [1]:
import pandas as pd

Ingestão & Análise Exploratória dos dados

Importação dos datasets (04) para análise exploratória: <br> 
Bancos.xlsx // Movimentos.xlsx // PlanoContas.xlsx // SaldoAnterior.xlsx

01. Dataset Bancos

Criar dataframe e visualizar as primeiras linhas: <br>
Obs.: Foi necessário instalar a lib. "openpyxl", para corrigir erro referente a encontrar o caminho do arquivo na pasta do projeto.

In [5]:
df_bancos = pd.read_excel('C:/Users/Usuário/Documents/_rma/_tecnologia/_data/evolve_data/projetos/fluxo_de_caixa_python_uv_sql/data/Bancos.xlsx', sheet_name='Bancos')
df_bancos.head()

   Banco_ID          Banco
0         1  Itau Unibanco
1         2       Bradesco
2         3          Inter

Verificar os tipos de dados e colunas do dataframe:

In [6]:
df_bancos.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Banco_ID  3 non-null      int64
 1   Banco     3 non-null      str
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

Verificar valores nulos do dataframe:

In [7]:
df_bancos.isnull().sum()

Banco_ID    0
Banco       0
dtype: int64

Verificar valores duplicados:

In [10]:
duplicated_values_df_bancos = df_bancos.duplicated().sum()
print(f'Número de valores duplicados no DataFrame: {duplicated_values_df_bancos}')

Número de valores duplicados no DataFrame: 0

Verificar a estatística das colunas textuais do dataframe:

In [11]:
df_bancos.describe(include='object')

C:\Users\Usuário\AppData\Local\Temp\ipykernel_16192\1598941106.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_bancos.describe(include='object')

                Banco
count               3
unique              3
top     Itau Unibanco
freq                1