Para este projeto, será utilizado o gerenciador de pacotes Python chamado "uv". <br>
Documentação: https://docs.astral.sh/uv/

De forma inicial: uv init <br>
(Versionamento do projeto com git e cria uma estrutura organizada de pastas, exemplo: .venv // .gitignore // .python-version // main.py // pyproject.toml // README.md)

uv add pandas <br>
uv add numpy <br>
(Ao adicionar bibliotecas ao projeto, as bibliotecas são adicionadas no arquivo pyproject.toml. A cada inserção/atualização de bibliotecas, o arquivo .toml é atualizado)

Importando as bibliotecas Python:

In [6]:
import pandas as pd

PARTE 01 - INGESTÃO & ANÁLISE EXPLORATÓRIA DOS DADOS

Importação dos datasets (04) para análise exploratória: <br> 
Bancos.xlsx // Movimentos.xlsx // PlanoContas.xlsx // SaldoAnterior.xlsx

01. Dataset Bancos

Criar dataframe e visualizar as primeiras linhas: <br>
Obs.: Foi necessário instalar a lib. "openpyxl", para corrigir erro por não encontrar o caminho do arquivo na pasta do projeto.

In [7]:
df_bancos = pd.read_excel('C:/Users/Usuário/Documents/_rma/_tecnologia/_data/evolve_data/projetos/fluxo_de_caixa_python_uv_sql/data/Bancos.xlsx', sheet_name='Bancos')
df_bancos.head()

   Banco_ID          Banco
0         1  Itau Unibanco
1         2       Bradesco
2         3          Inter

Verificar os tipos de dados e colunas do dataframe:

In [8]:
df_bancos.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Banco_ID  3 non-null      int64
 1   Banco     3 non-null      str
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

Verificar valores nulos do dataframe:

In [9]:
df_bancos.isnull().sum()

Banco_ID    0
Banco       0
dtype: int64

Verificar valores duplicados:

In [10]:
duplicated_values_df_bancos = df_bancos.duplicated().sum()
print(f'Número de valores duplicados no DataFrame: {duplicated_values_df_bancos}')

Número de valores duplicados no DataFrame: 0

Verificar a estatística das colunas textuais do dataframe:

In [11]:
df_bancos.describe(include='object')

C:\Users\Usuário\AppData\Local\Temp\ipykernel_15064\1598941106.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_bancos.describe(include='object')

                Banco
count               3
unique              3
top     Itau Unibanco
freq                1

02. Dataset PlanoContas

Criar dataframe e visualizar as primeiras linhas:

In [12]:
df_plano_contas = pd.read_excel('C:/Users/Usuário/Documents/_rma/_tecnologia/_data/evolve_data/projetos/fluxo_de_caixa_python_uv_sql/data/PlanoContas.xlsx', sheet_name='PlanoContas')
df_plano_contas.head()

   Subgrupo_ID                  Subgrupo  Conta_ID                       Conta
0         1100       Receitas com vendas      1101          Vendas de produtos
1         1200      Receitas financeiras      1201       Receita de aplicações
2         1200      Receitas financeiras      1202  Transferências de entradas
3         2100  Pagamento a fornecedores      2101               Matéria-prima
4         2100  Pagamento a fornecedores      2102            Energia elétrica

Verificar os tipos de dados e colunas do dataframe:

In [13]:
df_plano_contas.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Subgrupo_ID  27 non-null     int64
 1   Subgrupo     27 non-null     str
 2   Conta_ID     27 non-null     int64
 3   Conta        27 non-null     str
dtypes: int64(2), str(2)
memory usage: 996.0 bytes

Verificar valores nulos do dataframe:

In [14]:
df_plano_contas.isnull().sum()

Subgrupo_ID    0
Subgrupo       0
Conta_ID       0
Conta          0
dtype: int64

Verificar valores duplicados:

In [15]:
duplicated_values_df_plano_contas = df_plano_contas.duplicated().sum()
print(f'Número de valores duplicados no DataFrame: {duplicated_values_df_plano_contas}')

Número de valores duplicados no DataFrame: 0

Verificar a estatística das colunas textuais do dataframe:

In [16]:
df_plano_contas.describe(include='object')

C:\Users\Usuário\AppData\Local\Temp\ipykernel_15064\505977035.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_plano_contas.describe(include='object')

                        Subgrupo               Conta
count                         27                  27
unique                         7                  27
top     Pagamento a fornecedores  Vendas de produtos
freq                          12                   1

03. Dataset Movimentos

Criar dataframe e visualizar as primeiras linhas:

In [17]:
df_movimentos = pd.read_excel('C:/Users/Usuário/Documents/_rma/_tecnologia/_data/evolve_data/projetos/fluxo_de_caixa_python_uv_sql/data/Movimentos.xlsx', sheet_name='Movimentos')
df_movimentos.head()

       Tipo               Conta       Data          Banco        Valor
0  Entradas  Vendas de produtos 2023-01-02  Itau Unibanco   4201365.79
1    Saídas              Fretes 2023-01-02  Itau Unibanco     -2211.34
2    Saídas            Salários 2023-01-02  Itau Unibanco -10380086.42
3    Saídas            Encargos 2023-01-02  Itau Unibanco  -4040434.14
4    Saídas          Benefícios 2023-01-02  Itau Unibanco  -4003418.21

Verificar os tipos de dados e colunas do dataframe:

In [18]:
df_movimentos.info()

<class 'pandas.DataFrame'>
RangeIndex: 14931 entries, 0 to 14930
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tipo    14931 non-null  str
 1   Conta   14931 non-null  str
 2   Data    14931 non-null  datetime64[us]
 3   Banco   14931 non-null  str
 4   Valor   14931 non-null  float64
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 583.4 KB

Verificar valores nulos do dataframe:

In [19]:
df_movimentos.isnull().sum()

Tipo     0
Conta    0
Data     0
Banco    0
Valor    0
dtype: int64

Verificar valores duplicados:

In [20]:
duplicated_values_df_movimentos = df_movimentos.duplicated().sum()
print(f'Número de valores duplicados no DataFrame: {duplicated_values_df_movimentos}')

Número de valores duplicados no DataFrame: 0

Verificar a estatística das colunas numéricas do dataframe:

In [21]:
df_movimentos['Valor'].describe().round(2)

count       14931.00
mean         -393.56
std        924958.52
min     -11000000.00
25%          -879.02
50%           -28.97
75%             0.00
max      11000000.00
Name: Valor, dtype: float64

Verificar a estatística das colunas textuais do dataframe:

In [22]:
df_movimentos.describe(include='object')

C:\Users\Usuário\AppData\Local\Temp\ipykernel_15064\3136837525.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_movimentos.describe(include='object')

          Tipo               Conta          Banco
count    14931               14931          14931
unique       2                  27              3
top     Saídas  Vendas de produtos  Itau Unibanco
freq     11871                1020           4977

04. Dataset SaldoAnterior

Criar dataframe e visualizar as primeiras linhas:

In [23]:
df_saldo_anterior = pd.read_excel('C:/Users/Usuário/Documents/_rma/_tecnologia/_data/evolve_data/projetos/fluxo_de_caixa_python_uv_sql/data/SaldoAnterior.xlsx', sheet_name='SaldoAnterior')
df_saldo_anterior.head()

   Banco_ID    Valor
0         1  5000000
1         2 -1000000
2         3   500000

Verificar os tipos de dados e colunas do dataframe:

In [24]:
df_saldo_anterior.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Banco_ID  3 non-null      int64
 1   Valor     3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

Verificar valores nulos do dataframe:

In [25]:
df_saldo_anterior.isnull().sum()

Banco_ID    0
Valor       0
dtype: int64

Verificar valores duplicados:

In [26]:
duplicated_values_df_saldo_anterior = df_saldo_anterior.duplicated().sum()
print(f'Número de valores duplicados no DataFrame: {duplicated_values_df_saldo_anterior}')

Número de valores duplicados no DataFrame: 0

Verificar a estatística das colunas numéricas do dataframe:

In [27]:
df_saldo_anterior['Valor'].describe().round(1)

count          3.0
mean     1500000.0
std      3122499.0
min     -1000000.0
25%      -250000.0
50%       500000.0
75%      2750000.0
max      5000000.0
Name: Valor, dtype: float64

Resumo DataFrames (Tabelas) criados: <br>
- df_bancos
- df_plano_contas
- df_movimentos
- df_saldo_anterior

PARTE 02 - CONEXÃO COM BANCO DE DADOS

uv add sqlalchemy psycopg2 --default-index https://pypi.org/simple/

Install e Import bibliotecas `dotenv e os` para armazenar dados sensíveis, ex.: senhas

uv add python-dotenv

In [68]:
import os
from dotenv import load_dotenv
load_dotenv()

True

Criar banco de dados no PostgreSQL (pgAdmin 4): <br>
db_cash_flow_uv

In [78]:
db_password = os.getenv("DB_PASSWORD")

In [80]:
from sqlalchemy import create_engine

# Conexão
usuario = "postgres"
senha = db_password
host = "localhost"
porta = "5432"
banco = "db_cash_flow_uv"

# Criando engine de conexão
engine = create_engine(f"postgresql+psycopg2://{usuario}:{senha}@{host}:{porta}/{banco}")

Etapa para enviar os DataFrames para o banco de dados "db_cash_flow_uv" no PostgreSQL (pgAdmin 4).

In [81]:
nome_tabela_1 = "bancos"
nome_tabela_2 = "plano_contas"
nome_tabela_3 = "movimentos"
nome_tabela_4 = "saldo_anterior"

df_bancos.to_sql(nome_tabela_1, engine, if_exists='replace', index=False)
df_plano_contas.to_sql(nome_tabela_2, engine, if_exists='replace', index=False)
df_movimentos.to_sql(nome_tabela_3, engine, if_exists='replace', index=False)
df_saldo_anterior.to_sql(nome_tabela_4, engine, if_exists='replace', index=False)

3